FULL_TIME_CONTRACT: str = "UGOVOR O RADU NA\nNEODREĐENO VRIJEME"

PART_TIME_CONTRACT: str = "UGOVOR O RADU NA\nODREĐENO VRIJEME"

RESET_TO_DEFAULTS: str = "PONOVNO POSTAVI POLJA"

PRINT: str = "PRINT"

GENERATE_PDF: str = "GENERATE PDF"

VALIDATE_CONTRACT: str = "VALIDATE CONTRACT"

EMPLOYERS: str = "POSLODAVCI"
