FULL_TIME_CONTRACT: str = "UGOVOR O RADU NA\nNEODREĐENO VRIJEME"

PART_TIME_CONTRACT: str = "UGOVOR O RADU NA\nODREĐENO VRIJEME"

CLEAR_FIELD: str = "CLEAR FIELDS"

PRINT: str = "PRINT"

GENERATE_PDF: str = "GENERATE PDF"

VALIDATE_CONTRACT: str = "VALIDATE CONTRACT"
