label_1: str = ", zastupano po direktoru"
label_2: str = "(u daljnjem tekstu: Poslodavac)"
label_3: str = "i"
label_4: str = "(u daljnjem tekstu: radnik), zaključili su sljedeći:"
label_5: str = "ANEKS UGOVORA O RADU"
label_6: str = "Članak I."
label_7: str = "1. Ugovorne strane suglasno utvrđuju da ovim Aneksom ugovaraju prava i obveze za vrijeme trajanja rada u inozemstvu."
label_8: str = "Članak II."
label_9: str = "1. Ugovorne strane suglasno utvrđuju da su dana"
label_10: str = "sklopile Ugovor o radu na"
label_11: str = "2. Predviđeno trajanje radnika u inozemstvu biti će do"
label_12: str = ", odnosno do završetka projekta/radova."
label_13: str = (
    "3. Nakon završetka razdoblja iz članka 2. stavak 2. poslodavac će osigurati radniku povratak u Hrvatsku."
)
label_14: str = "Članak III."
label_15: str = "1. Mjesto rada radnika biti će  u pravilu u"
label_16_1: str = ", ali je suglasan da po i sukladno"
label_16_2: str = "te potrebama poslodavca poslove obavlja i na drugim mjestima na čitavom teritoriju Europske unije kao i da putuje u inozemstvo radi izvršavanja povjerenih mu poslova."
label_17: str = "Članak IV."
label_18_1: str = "1. Radnik će obavljati poslove koji s obzirom na organizaciju rada, interna pravila, upute korisnika, poslovna pravila i standarde struke u skladu s naravi i vrstom"
label_18_2: str = "posla za koje je zasnovan radni odnos, kao sve poslove koji mu je privremeno ili trajno, povjeri naručitelj ili koji mu u ime naručitelja naloži radnik naručitelja."
label_19: str = "2. Radnik će obavljati poslove"
label_20_1: str = ", ali je dužan obavljati i sve ostale poslove koji su s obzirom na"
label_20_2: str = "organizaciju rada, interna pravila, upute korisnika, poslovna pravila i standarde struke u skladu s naravi iv vrstom posla za koje je zasnovan radni odnos, kao sve"
label_20_3: str = "poslove koji mu privremeno ili trajno povjeri naručitelj ili kojih mu u ime naručitelja naloži nadređeni radnik naručitelja."
label_21: str = "Članak V."
label_22: str = "1. Radnik je za vrijeme trajanja rada u državi izaslanja dužan poštivati propise, običaje i okruženje države u koju je izaslan."
label_23: str = "2. Radnik potpisom ovog aneksa potvrđujem da je upoznat s radnom, uvjetima rada, pravima i obvezama radnika u državi izaslanja. "
label_24: str = "Članak VI."
label_25_1: str = "1. Radnik će raditi u punom radnom vremenu u trajanju od 40 sati tjedno, a koje je raspoređeno u pravilu od ponedjeljka do petak/subote te se prilagođava organizaciji"
label_25_2: str = "rada na radilištu."
label_26: str = "2.Pravo na stanku određuje se u trajanju od 30 minuta te će se korištenjem iste prilagoditi organizaciji i potrebama rada na radilištu."
label_27: str = "Članak VII."
label_28: str = "1. Za vrijeme trajanja rada u inozemstvu te na području gdje će radnik obavljati rad, neradni dani i blagdani su NERADNI."
label_29: str = "Članak VIII."
label_30_1: str = "1. Za obavljeni rad za vrijeme trajanja izaslanja poslodavac će isplaćivati radniku mjesečnu plaću u kunama koja se sastoji od bruto plaće sukladno Ugovoru o radu te"
label_30_2: str = "će se mjesečna osnovica za plaćanje doprinosa uvećati za 20% i ostala primanja u novcu i naravi na koja radnik ima pravo za vrijeme rada u inozemstvu"
label_30_3: str = (
    "(ili minimalne stanice/plaće koja se isplaćuje sukladno zakonodavstvu države u kojoj radnik obavlja rad)."
)
label_31: str = "Članak IX."
label_32_1: str = "1. U slučaju da se za vrijeme trajanja ovog aneksa radnik privremeno ne obavlja rad u državi izaslanja te se vrati u RH, istom za to vrijeme pripada samo bruto"
label_32_2: str = "plaća iz Ugovora o radu."
label_33_1: str = "2. U slučaju da radnik, iz bolo kojeg razloga, trajno ne obavlja rad u državi izaslanja te se vrati u RH smatra se da ovaj aneks prestaje vrijediti s danom prestanka"
label_33_2: str = "rada u državi u koju je izaslan."
label_34: str = "Članak X."
label_35: str = (
    "1. Ugovorne strane suglasno utvrđuju da će sve izmjene i dopune ovog ugovora sastaviti u pisanom obliku."
)
label_36: str = "Članak XI."
label_37_1: str = "1. Ugovorne strane suglasne su da će sve eventualne sporove glede odredbi ovog ugovora riješiti sporazumno, a ukoliko to nije moguće ugovaraju nadležnost"
label_37_2: str = "Općinskog suda u"
label_38: str = "Članak XII."
label_39: str = (
    "1. Ovaj ugovor sastavljen je u dva istovjetna primjerka od kojih svaka ugovorna strana zadržava po jedan primjerak"
)
label_40: str = "Članak XIII."
label_41_1: str = "1. Strane su suglasne da je u odredbama ovog ugovora sadržana njihova stvarna bolja, očitovana slobodno i ozbiljno, te ga u znak prihvata prava i obveza koje iz njega"
label_41_2: str = "proizlaze vlastoručno potpisuju."
label_42: str = "U"
label_43: str = ", dana"
label_44: str = "godine."
label_45: str = "Poslodavac"
label_46: str = "Radnik"
