WRITE: str = "normal"
READ_ONLY: str = "readonly"

DELETE: str = "end"

JOB_DESCRIPTION_DEFAULT: str = "POSAO - OPIS POSLA"

WORK_PLACE_DEFAULT = "NASELJE/GRAD/OPĆINA U KOJEM SE RADI"

START_DATE_DESCRIPTION_DEFAULT: str = "OPIS POČETKA RADA"

SALARY_DEFAUL: str = "0.00"

RIGHTS_AND_OBLIGATIONS_DEFAULT: str = "prema Zakonu o radu"

DASH_DEFAULT: str = "(-)"

WORKING_SHIFT_DESCRIPTION_DEFAULT: str = "OPIS RADNOG VREMENA"
