APPLICATION_TITLE: str = "KNJIGOVODSTVENI ASISTENT"

EMPLOYER_NAME: str = "NAZIV POSLODAVCA"

NAME: str = "IME"

LASTNAME: str = "PREZIME"

STREET: str = "ULICA"

CITY: str = "GRAD/OPĆINA"

POTSAL: str = "POŠTANSKI BROJ"

EMPLOYER_VAT: str = "OIB/POREZNI BROJ"

EMPLOYEE_PERSONAL_ID: str = "OIB/PUTOVNICA"

EMPLOYERS: str = "POSLODAVCI"

EMPLOYER_DIRECTOR: str = "ODGOVORNA OSOBA"

EMPLOYER_LIST: str = "LISTA POSLODAVACA"

EMPLOYEE_EMPLOYER_LST: str = "LISTA POSLODAVACA ZAPOSLENOG"
