label_1: str = "Između"
label_2: str = "kojeg zastupa"
label_3: str = "(dalje: Poslodavac) i"
label_4: str = "(dalje: Radnik) dana"
label_5: str = "sklopljen je"
label_6: str = "UGOVOR O RADU NA ODREĐENO VRIJEME"
label_7: str = "I. Opće odredbe"
label_8: str = (
    "1. Ovim se Ugovorom utvrđuju međusobna prava, obveze i odgovornosti na radu između Poslodavca i Radnika."
)
label_9: str = "2. Ovim Ugovorom Radnik zasniva radni odnos na određeno vrijeme do"
label_10: str = "za obavljanje poslova"
label_11: str = "3. Ugovorne stranke ugovaraju probni rad Radnika u trajanju od"
label_12: str = "mjeseca/i."
label_13: str = "4. Mjesto rada Radnika je u"
label_14: str = ", a u slučaju potrebe Poslodavca i u nekom drugom mjestu na području Republike Hrvatske."
label_15: str = "5. Pored poslova navedenih u točki 2. ovog Ugovora, Radnik će obavljati i druge poslove prema nalogu Poslodavca, a koji su u skladu naravi i vrsti posla za koje je zasnovan radni odnos."
label_16: str = "6. Radnik počinje s radom"
label_17: str = "."
label_18: str = "II. Plaće i naknade"
label_19: str = "1. Za realizaciju preuzetih obveza iz točke I.2. Radniku pripada osnovna bruto plaća u iznosu od"
label_20: str = "eura."
label_21: str = ""
label_22: str = "2. Isplata će se obavljati jedanput  mjesečno i to najkasnije do 15-tog u mjesecu za prethodni mjesec."
label_23: str = "3. Uz plaću navedenu u točki II.1. ovog Ugovora, Radniku pripada i stimulativni dio plaće u iznosu od"
label_24: str = "eura bruto mjesečno"
label_25: str = "4. Radnik ima pravo na povećanu plaću za"
label_26: str = "- otežane uvjete rada"
label_27: str = "- rad u dane blagdana i neradne dane utvrđene zakonom i za rad na dan Uskrsa"
label_28: str = "- rad nedjeljom"
label_29: str = "- noćni rad"
label_30: str = "- prekovremeni rad"
label_31: str = "- za rad u drugoj smjeni u slučaju stalnog smjenskog rada"
label_32: str = "III. Troškovi i naknade"
label_33: str = (
    "1. Radnik ima pravo naknade troškova za službena putovanja u zemlji i inozemstvu, u visini propisanoj zakonom."
)
label_34: str = "IV. Radno vrijeme i godišnji odmor"
label_35: str = "1. Radnik će raditi"
label_36: str = "radno vrijeme od"
label_37: str = "sati tjedno."
label_38: str = "2. Radno vrijeme određuje se"
label_39: str = ", te počinje-završava"
label_40: str = "3. U tijeku rada Radnik ima pravo koristiti dnevni odmor (stanku) u trajanju od 30 minuta."
label_41: str = "4. Tjedni odmor Radnik će koristiti"
label_42: str = "5. Radnik ima pravo na godišnji odmor u trajanju od"
label_43: str = "V. Čuvanje poslovne tajne"
label_44: str = "1, Radnik se obvezuje da će za vrijeme trajnja Ugovora o radu, a i njegovo prestanka, čuvati sve poslovne tajne Poslodavca i njegovih komitenata\nprema neovlaštenim osobama,  koje su po svojoj prirodi povjerene i zaštićene, a koje su mu bile povjerene ili koje je mogao saznati na poslu."
label_45: str = ""
label_46: str = "VI. Otkaz ugovora o radu"
label_47: str = "1. Ovaj Ugovor"
label_48: str = " redovito otkazati i Poslodavac i Radnik pod uvjetima propisanim zakonom, i prije isteka vremena na  koji je  sklopljen."
label_49: str = "2. U slučaju kad Poslodavac redovito otkazuje, otkazni rok iznosi"
label_50: str = "dana, a su slučaju kad redovito otokazuje Radnik, otkazni rok je"
label_51: str = "dana."
label_52: str = "VII. Ostala prava i ovbeze Radnika i Poslodavca"
label_53: str = "VIII. Zaključne odredbe"
label_54: str = "1. Za slučaj spora, stranke ugovaraju mjesnu nadležnost suda u"
label_55: str = "2. Ovaj Ugovor stupa na snagu"
label_56: str = (
    "3. Ovaj je Ugovor sastavljen u 3 jednaka primjerka od kojih Poslodavac zadržava 2, a Radnik jedan primjerak."
)
