WRITE: str = "normal"

READ_ONLY: str = "readonly"

DELETE: str = "end"

JOB_DESCRIPTION_DEFAULT: str = "POSAO - OPIS POSLA"

WORK_PLACE_DEFAULT = "NASELJE/GRAD/OPĆINA U KOJEM SE RADI"

START_DATE_DESCRIPTION_DEFAULT: str = "OPIS POČETKA RADA"

END_JOB_DATE_DESCRIPTION_DEFAULT: str = "OPIS KRAJA UGOVORA"

CONTRACT_STARTS_WITH_DESCRIPTION_DEFAULT: str = "OPIS UGOVORA STUPANJA NA SNAGU"

SALARY_DEFAULT: str = "0.00"

PLACE_DEFAULT: str = "Mjesto"

RIGHTS_AND_OBLIGATIONS_DEFAULT: str = "Ostala prava i obveze utvrđuju se prema Zakonu o radu"

DASH_DEFAULT: str = "(-)"

WORKING_SHIFT_DESCRIPTION_DEFAULT: str = "OPIS RADNOG VREMENA"

__PERCENGATE: str = "%"

PERCENTAGE_20: str = f"20{__PERCENGATE}"
PERCENTAGE_30: str = f"30{__PERCENGATE}"
PERCENTAGE_50: str = f"50{__PERCENGATE}"
