TWO_DECIMALS_REGEX = r"^0\.00"
# ONE_DECIMAL_REGEX = r"^0\.0"
ONE_DECIMAL_REGEX = r"^0\.0[1-9]"
DECIMAL_SEPARATOR_REGEX = r"\."

BACKSPACE_TWO_DECIMAL_REGEX = r"^[0-9]\.[0-9]$"
BACKSPACE_ONE_DECIMAL_REGEX = r"^0\.0$"
